/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainScreenForm;

/**
 *
 * @author akhil
 */

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class AQI_data4 extends javax.swing.JFrame {

	/**
	 * Creates new form AQI_data4
	 */
	public AQI_data4() {
		initComponents();
                jPanel1.setVisible(true);
                jPanel2.setVisible(false);
	}
        Sensor_choice sens = new Sensor_choice();

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 =  new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    AQI_data4.class.getResource("/images/img1.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        }; ;
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        sub_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        detect_data_btn = new javax.swing.JButton();
        no2_data = new javax.swing.JTextField();
        pm10_data = new javax.swing.JTextField();
        o3_data = new javax.swing.JTextField();
        pm25_data = new javax.swing.JTextField();
        temp_data = new javax.swing.JTextField();
        hum_data = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        res_aqi_data = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        qlty_data = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cool_sys_data = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADMIN BLOCK Sensor Data");

        jPanel1.setPreferredSize(new java.awt.Dimension(629, 651));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("<html>Hourly Pollutant Gas Density (in µg/m<sup>3</sup>)</html>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("<html>NO<sub>2</sub></html>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("<html>PM<sub>10</sub></html>");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("<html>O<sub>3</sub></html>");
        jLabel4.setToolTipText("<html>O<sub>3</sub></html>\n");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("<html>PM<sub>2.5</sub></html>");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("<html>Temperature<br>(°C)</html>");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("<html>Humidity<br>(%)</html>");

        cancel_btn.setBackground(new java.awt.Color(0, 102, 153));
        cancel_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cancel_btn.setForeground(new java.awt.Color(204, 255, 255));
        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        cancel_btn.setText("CANCEL");
        cancel_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancel_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        cancel_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancel_btnKeyPressed(evt);
            }
        });

        reset_btn.setBackground(new java.awt.Color(0, 102, 153));
        reset_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        reset_btn.setForeground(new java.awt.Color(204, 255, 255));
        reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        reset_btn.setText("HISTORY");
        reset_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        reset_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reset_btnKeyPressed(evt);
            }
        });

        sub_btn.setBackground(new java.awt.Color(0, 102, 153));
        sub_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        sub_btn.setForeground(new java.awt.Color(204, 253, 253));
        sub_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        sub_btn.setText("SUBMIT");
        sub_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sub_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btnActionPerformed(evt);
            }
        });
        sub_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sub_btnKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Admin Block");

        detect_data_btn.setBackground(new java.awt.Color(0, 102, 153));
        detect_data_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        detect_data_btn.setForeground(new java.awt.Color(204, 255, 255));
        detect_data_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/select.png"))); // NOI18N
        detect_data_btn.setText("Detect Data");
        detect_data_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detect_data_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detect_data_btn.setNextFocusableComponent(cancel_btn);
        detect_data_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detect_data_btnActionPerformed(evt);
            }
        });
        detect_data_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                detect_data_btnKeyPressed(evt);
            }
        });

        no2_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2_dataActionPerformed(evt);
            }
        });

        o3_data.setText("                 ");

        pm25_data.setText("                 ");

        temp_data.setText("                  ");

        hum_data.setText("                 ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Qualitative Name");

        res_aqi_data.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        res_aqi_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        res_aqi_data.setText("                                    ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("<html>Resultant Index/<br>Sub-Index</html>");

        qlty_data.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        qlty_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qlty_data.setText("                                                 ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("<html>Central Cooling<br>System Setting</html>");

        cool_sys_data.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        cool_sys_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cool_sys_data.setText("                                       ");
        cool_sys_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cool_sys_dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pm10_data, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(no2_data)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hum_data)
                                    .addComponent(o3_data, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(temp_data, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pm25_data, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(res_aqi_data, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qlty_data, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(cool_sys_data)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(detect_data_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detect_data_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no2_data, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 51, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pm10_data, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(res_aqi_data, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qlty_data, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cool_sys_data, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hum_data, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_btn)
                    .addComponent(cancel_btn)
                    .addComponent(sub_btn))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(o3_data, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pm25_data, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temp_data, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cool_sys_data, jLabel11});

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));
        jTable1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date:Time", "<html>NO<sub>2</sub></html>", "<html>PM<sub>10</sub></html>", "<html>O<sub>3</sub></html>", "<html>PM<sub>2.5</sub></html>", "AQI"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(123);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(123);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(123);
            jTable1.getColumnModel().getColumn(1).setMinWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(2).setMinWidth(60);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(3).setMinWidth(60);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(4).setMinWidth(60);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(5).setMinWidth(60);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        Back.setBackground(new java.awt.Color(0, 102, 153));
        Back.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        Back.setForeground(new java.awt.Color(204, 253, 253));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Ebrima", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 253, 253));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jLabel12.setText("ADMIN BLOCK LOG DATA REPORT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(90, 90, 90))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Back))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
        private class admin_sensorData{
                DecimalFormat df = new DecimalFormat("0.00");
                double rand_no2;
                double rand_pm10;
                double rand_o3;
                double rand_pm25;
                double rand_temp;
                double rand_hum;
                double no2, pm10, o3, pm25, temp, hum, aqi_idx, avg_aqi;
                
                public void randGen(){
                        Random rand = new Random();
                        rand_no2 = 500*rand.nextDouble();
                        rand_pm10 = 300*rand.nextDouble();
                        rand_o3 = 360*rand.nextDouble();
                        rand_pm25 = 200*rand.nextDouble();
                        rand_temp = -5 + 60*rand.nextDouble();
                        rand_hum = 100*rand.nextDouble();
                        avg_aqi = (rand_no2 + rand_pm10 + 
                                        rand_o3 + rand_pm25)/4;
                }
                
                public void dataValue() {
                        no2 = Double.parseDouble(df.format(rand_no2));
                        pm10 = Double.parseDouble(df.format(rand_pm10));
                        o3 = Double.parseDouble(df.format(rand_o3));
                        pm25 = Double.parseDouble(df.format(rand_pm25));
                        temp = Double.parseDouble(df.format(rand_temp));
                        hum = Double.parseDouble(df.format(rand_hum));

                        no2_data.setText("" + no2);
                        pm10_data.setText("" + pm10);
                        o3_data.setText("" + o3);
                        pm25_data.setText("" + pm25);
                        temp_data.setText("" + temp);
                        hum_data.setText("" + hum);
                        res_aqi_data.setText("");
                        qlty_data.setText("");
                        qlty_data.setForeground(Color.white);
                        cool_sys_data.setText("");
                        
                        aqi_idx = Double.parseDouble(df.format(avg_aqi));
                       res_aqi_data.setText("" + aqi_idx);

                       if(aqi_idx>0 && aqi_idx<=50){
                           qlty_data.setText("GOOD");
                           qlty_data.setForeground(Color.green);
                       }
                       else if(aqi_idx>50 && aqi_idx<=100){
                           qlty_data.setText("MODERATE");
                           qlty_data.setForeground(Color.yellow);
                       }
                       else if(aqi_idx>100 && aqi_idx<=150){
                           qlty_data.setText("UNHEALTHY");
                           qlty_data.setForeground(Color.blue);
                       }
                       else if(aqi_idx>150 && aqi_idx<=200){
                           qlty_data.setText("VERY UNHEALTHY");
                           qlty_data.setForeground(Color.red);
                       }
                       else{
                           qlty_data.setText("HAZARDOUS");
                           qlty_data.setForeground(Color.magenta);
                       }

                }
                
                public void decision(){    
                       if(temp<=15 && hum>70) {
                           cool_sys_data.setText("Increase A/C Temp");
                       }
                       else if((temp>=25 && hum>40) || temp>=40) {
                           cool_sys_data.setText("Lower A/C Temp");
                       }
                       else {
                           cool_sys_data.setText("Default Setting");
                       }
                       
                       if (aqi_idx > 200) {
                           JDialog.setDefaultLookAndFeelDecorated(true);
                           String[] email = {"YES","NO"};

                           String x=(String)JOptionPane.showInputDialog(null,
                                   "<html><b>"
                                   + "HAZARDOUS AIR QUALITY DETECTED.</b><br>"
                                   + " Central Cooling System Setting : "
                                   + "<b>"+cool_sys_data.getText()
                                   + "<br><br>Do you want to <b>alert</b> the"
                                   + " authority by sending <b>E-MAIL</b> ?<br>"
                                   + "<br></html>"
                                   ,"WARNING"
                                   ,JOptionPane.WARNING_MESSAGE
                                   ,null
                                   ,email
                                   ,email[0]);
                           
                           if(x.equals("YES")){
                               JOptionPane.showMessageDialog(null,
                                       "E-Mail Sent Successfully",
                                       "Confirmation", JOptionPane.PLAIN_MESSAGE);
                               mail.main(null);
                           }
                       }
                       
                }
                
                public void resetData() {
                    no2_data.setText("");
                    pm10_data.setText("");
                    o3_data.setText("");
                    pm25_data.setText("");
                    temp_data.setText("");
                    hum_data.setText("");
                    res_aqi_data.setText("");
                    qlty_data.setText("");
                    qlty_data.setForeground(Color.white);
                    cool_sys_data.setText("");
                }
                
        }
    
        admin_sensorData admin = new admin_sensorData();
        SimpleDateFormat dateFormat = new SimpleDateFormat(""
                        + "yyyy-MM-dd::HH:mm:ss");
        String admin_datetime;
        
        private void sub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btnActionPerformed
                admin.decision();
                DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
                String data[]={admin_datetime,Double.toString(admin.no2),
                    Double.toString(admin.pm10),Double.toString(admin.o3),
                    Double.toString(admin.pm25),Double.toString(admin.aqi_idx)};
                tbmodel.addRow(data);
        }//GEN-LAST:event_sub_btnActionPerformed

        private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
		sens.setVisible(true);
                dispose();
        }//GEN-LAST:event_cancel_btnActionPerformed

        private void no2_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2_dataActionPerformed
        }//GEN-LAST:event_no2_dataActionPerformed

    private void detect_data_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detect_data_btnActionPerformed
                admin_datetime = dateFormat.format(new Date());
                admin.randGen();
                admin.dataValue();
    }//GEN-LAST:event_detect_data_btnActionPerformed

    private void cool_sys_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cool_sys_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cool_sys_dataActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
                jPanel1.setVisible(false);
                jPanel2.setVisible(true);
    }//GEN-LAST:event_reset_btnActionPerformed

    private void detect_data_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_detect_data_btnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
                admin.randGen();
                admin.dataValue();
        }
    }//GEN-LAST:event_detect_data_btnKeyPressed

    private void cancel_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancel_btnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
                sens.setVisible(true);
                dispose();
        }
    }//GEN-LAST:event_cancel_btnKeyPressed

    private void reset_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reset_btnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
                jPanel1.setVisible(false);
                jPanel2.setVisible(true);
        }
    }//GEN-LAST:event_reset_btnKeyPressed

    private void sub_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub_btnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
                admin.decision();
                DefaultTableModel tbmodel=(DefaultTableModel)jTable1.getModel();
                String data[]={admin_datetime,Double.toString(admin.no2),
                    Double.toString(admin.pm10),Double.toString(admin.o3),
                    Double.toString(admin.pm25),Double.toString(admin.aqi_idx)};
                tbmodel.addRow(data);
        }
    }//GEN-LAST:event_sub_btnKeyPressed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
                jPanel2.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MessageFormat header = new MessageFormat("Admin Block Log Report");
       
       MessageFormat footer = new MessageFormat("Page{0,number,integer}");
       try{
           jTable1.print(JTable.PrintMode.NORMAL,header,footer);
           
       }   catch (java.awt.print.PrinterException e){
           System.err.format("Cannot print %s%n", e.getMessage());
       }
    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AQI_data4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AQI_data4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AQI_data4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AQI_data4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new AQI_data4().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JTextField cool_sys_data;
    private javax.swing.JButton detect_data_btn;
    private javax.swing.JTextField hum_data;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField no2_data;
    private javax.swing.JTextField o3_data;
    private javax.swing.JTextField pm10_data;
    private javax.swing.JTextField pm25_data;
    private javax.swing.JTextField qlty_data;
    private javax.swing.JTextField res_aqi_data;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton sub_btn;
    private javax.swing.JTextField temp_data;
    // End of variables declaration//GEN-END:variables
}

