/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainScreenForm;

/**
 *
 * @author arpit
 */
 import java.awt.Graphics;  
 import java.awt.Image;  
 import java.awt.Toolkit;  
 import javax.swing.JPanel; 
 import javax.swing.ButtonGroup;
 import java.awt.Container;
 import java.awt.GridLayout;
 import java.awt.event.*;
 import javax.swing.*;

public class Screen1_choice extends javax.swing.JFrame {
	
	/**
	 * Creates new form Screen1_choice
	 */
	public Screen1_choice() {
		initComponents();
		}
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 =  new JPanel() {
            public void paintComponent(Graphics g) {
                Image img = Toolkit.getDefaultToolkit().getImage(
                    Screen1_choice.class.getResource("/images/back2.jpg"));
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);
            }
        };
        formHeading = new javax.swing.JLabel();
        new_rcd_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atmospheric Management System | Select Choice");

        formHeading.setBackground(new java.awt.Color(255, 255, 255));
        formHeading.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        formHeading.setForeground(new java.awt.Color(255, 255, 255));
        formHeading.setText("ATMOSPHERIC MANAGEMENT SYSTEM");

        new_rcd_btn.setBackground(new java.awt.Color(0, 102, 153));
        new_rcd_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        new_rcd_btn.setForeground(new java.awt.Color(204, 255, 255));
        new_rcd_btn.setText("Check Current Air Quality Index");
        new_rcd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_rcd_btnActionPerformed(evt);
            }
        });
        new_rcd_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_rcd_btnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(formHeading)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(new_rcd_btn)
                .addGap(104, 104, 104))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(formHeading)
                .addGap(62, 62, 62)
                .addComponent(new_rcd_btn)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_rcd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_rcd_btnActionPerformed
            this.toBack();
            Sensor_choice place = new Sensor_choice();
            place.setVisible(true);
            place.toFront();
    }//GEN-LAST:event_new_rcd_btnActionPerformed

    private void new_rcd_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_rcd_btnKeyPressed
            if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
                    this.toBack();
                    Sensor_choice place = new Sensor_choice();
                    place.setVisible(true);
                    place.toFront();   
            }
    }//GEN-LAST:event_new_rcd_btnKeyPressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
//			@Override
			public void run() {
				new Screen1_choice().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formHeading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton new_rcd_btn;
    // End of variables declaration//GEN-END:variables
}

