/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainScreenForm;

/**
 *
 * @author akhil
 */
 import java.awt.Graphics;  
 import java.awt.Image;  
 import java.awt.Toolkit;  
 import javax.swing.JPanel; 
 import javax.swing.ButtonGroup;
 import java.awt.Container;
 import java.awt.GridLayout;
 import java.awt.event.*;
 import javax.swing.*;

public class Screen1_choice extends javax.swing.JFrame {
	
	private void groupButton( ) {

		ButtonGroup bg1 = new ButtonGroup( );

		bg1.add(new_rcd_btn);
		bg1.add(prev_rec_btn);
	}


	
	/**
	 * Creates new form Screen1_choice
	 */
	public Screen1_choice() {
		initComponents();
		groupButton();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 =  new JPanel() {  
            public void paintComponent(Graphics g) {  
                Image img = Toolkit.getDefaultToolkit().getImage(  
                    Screen1_choice.class.getResource("/images/img2.jpg"));  
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);  
            }  
        };
        formHeading = new javax.swing.JLabel();
        prev_rec_btn = new javax.swing.JRadioButton();
        new_rcd_btn = new javax.swing.JRadioButton();
        clear_btn = new javax.swing.JButton();
        proceed_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atmospheric Management System | Select Choice");

        formHeading.setBackground(new java.awt.Color(255, 255, 255));
        formHeading.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        formHeading.setText("What do You want to do ?");

        prev_rec_btn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        prev_rec_btn.setText("View History");
        prev_rec_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prev_rec_btn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        prev_rec_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prev_rec_btnActionPerformed(evt);
            }
        });

        new_rcd_btn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        new_rcd_btn.setText("Check Current Air Quality Index");
        new_rcd_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        new_rcd_btn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        new_rcd_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_rcd_btnMouseClicked(evt);
            }
        });
        new_rcd_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_rcd_btnActionPerformed(evt);
            }
        });
        new_rcd_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                new_rcd_btnKeyPressed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(0, 102, 153));
        clear_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(204, 255, 255));
        clear_btn.setText("Clear Selection");
        clear_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear_btn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        clear_btn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                clear_btnItemStateChanged(evt);
            }
        });
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });
        clear_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clear_btnKeyPressed(evt);
            }
        });

        proceed_btn.setBackground(new java.awt.Color(0, 102, 153));
        proceed_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        proceed_btn.setForeground(new java.awt.Color(204, 255, 255));
        proceed_btn.setText("Proceed");
        proceed_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        proceed_btn.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        proceed_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceed_btnActionPerformed(evt);
            }
        });
        proceed_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                proceed_btnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(new_rcd_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_rec_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(proceed_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(formHeading))))
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(formHeading)
                .addGap(18, 18, 18)
                .addComponent(prev_rec_btn)
                .addGap(17, 17, 17)
                .addComponent(new_rcd_btn)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_btn)
                    .addComponent(proceed_btn))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void prev_rec_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prev_rec_btnActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_prev_rec_btnActionPerformed

        private void new_rcd_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_rcd_btnActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_new_rcd_btnActionPerformed

        private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
		if(new_rcd_btn.isSelected()){
			new_rcd_btn.setSelected(false);
			prev_rec_btn.setSelected(true);
		}
		else if(prev_rec_btn.isSelected()){
			new_rcd_btn.setSelected(true);
			prev_rec_btn.setSelected(false);
		}
        }//GEN-LAST:event_clear_btnActionPerformed

        private void clear_btnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_clear_btnItemStateChanged
//		if(new_rcd_btn.isSelected()|| prev_rec_btn.isSelected()){
//			new_rcd_btn.setSelected(false);
//			prev_rec_btn.setSelected(false);
//		}
        }//GEN-LAST:event_clear_btnItemStateChanged

        private void proceed_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceed_btnActionPerformed
 		if(new_rcd_btn.isSelected()){
			this.toBack();
			Sensor_choice place = new Sensor_choice();
			place.setVisible(true);
			place.toFront();
		}
        }//GEN-LAST:event_proceed_btnActionPerformed

        private void new_rcd_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_rcd_btnMouseClicked
        }//GEN-LAST:event_new_rcd_btnMouseClicked

    private void new_rcd_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_new_rcd_btnKeyPressed
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if(new_rcd_btn.isSelected()){
			this.toBack();
			Sensor_choice place = new Sensor_choice();
			place.setVisible(true);
			place.toFront();
		}
        }
    }//GEN-LAST:event_new_rcd_btnKeyPressed

    private void proceed_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_proceed_btnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if(new_rcd_btn.isSelected()){
			this.toBack();
			Sensor_choice place = new Sensor_choice();
			place.setVisible(true);
			place.toFront();
		}
        }
    }//GEN-LAST:event_proceed_btnKeyPressed

    private void clear_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clear_btnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if(new_rcd_btn.isSelected()){
			new_rcd_btn.setSelected(false);
			prev_rec_btn.setSelected(true);
		}
		else if(prev_rec_btn.isSelected()){
			new_rcd_btn.setSelected(true);
			prev_rec_btn.setSelected(false);
		}
        }
    }//GEN-LAST:event_clear_btnKeyPressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Screen1_choice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
//			@Override
			public void run() {
				new Screen1_choice().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel formHeading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton new_rcd_btn;
    private javax.swing.JRadioButton prev_rec_btn;
    private javax.swing.JButton proceed_btn;
    // End of variables declaration//GEN-END:variables
}

